# Generated by Django 5.1.5 on 2025-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='motor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
